services:

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-groupea}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-groupea}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-secret}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

# ----SUPERVISION AND MONITORING SERVICES----

  prometheus:
    image: prom/prometheus:latest
    container_name: gymflow_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: gymflow_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: gymflow-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

  node-exporter:
    image: prom/node-exporter:latest
    container_name: gymflow-node-exporter
    ports:
      - "9100:9100"
    restart: always

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: gymflow-mysqld-exporter
    volumes:
      - ./.my.cnf:/.my.cnf:ro
    command:
      - '--config.my-cnf=/.my.cnf'
    ports:
      - "9104:9104"
    depends_on:
      db:
        condition: service_healthy
    restart: always


  alertmanager:
    image: prom/alertmanager:latest
    container_name: gymflow-alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml.template
    ports:
      - "9093:9093"

    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "sh -c 'sed \"s|\\${SLACK_WEBHOOK_URL}|'\"$SLACK_WEBHOOK_URL\"'|g\" /etc/alertmanager/alertmanager.yml.template > /etc/alertmanager/alertmanager.yml && exec /bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml'"
    restart: always

volumes:
  db_data:
  grafana_data: